/*
Project Title: Assignment 3b
Date: Mon May  4 13:52:09 2026

EE P 598a: Advanced Topics In Electrical And Computer Engineering (Introduction to Digital Audio)
Authors: Joseph Anderson, Junkai Wu, et al.
Affiliation: DXARTS, University of Washington (https://dxarts.washington.edu/)
License: GPLv3 (https://www.gnu.org/licenses/gpl-3.0.en.html)
*/

// ---------------------------------
// Trumpet C4 _1_ forte normal

/*
TEST TONE

- import your own sample to use from the London Philharmonia Sample Library

*/


/*
trumpet_C4_1_forte_normal.mp3

Downloaded on Mon May  4 13:52:09 2026
Trumpet C4 _1_ forte normal
Performer: ??
Technicians: ??
https://philharmonia-assets.s3-eu-west-1.amazonaws.com/uploads/2020/02/12112005/Brass.zip
License: "You are free to use these samples as you wish, including releasing them as part of a commercial work. The only restriction is that they must not be sold or made available ‘as is’ (i.e. as samples or as a sampler instrument)."

See also:
https://philharmonia.co.uk/resources/sound-samples/
*/
