/*
Project Title: Assignment 3c
Date: Mon May  4 13:52:09 2026

EE P 598a: Advanced Topics In Electrical And Computer Engineering (Introduction to Digital Audio)
Authors: Joseph Anderson, Junkai Wu, et al.
Affiliation: DXARTS, University of Washington (https://dxarts.washington.edu/)
License: GPLv3 (https://www.gnu.org/licenses/gpl-3.0.en.html)
*/

/*
For examples see:

HelpBrowser.openLink("link::Tutorials/Getting Practice/ProjectSHARCWTsWPs::")
*/


// -------------------------
// instantiate CtkProtoNotes
~myPlayBufTransPNotes = CtkProtoNotes.new;  // protoNote dict for playing soundfiles


// -------------------------
// add synthDefs

~myPlayBufTransPNotes.add(

	/*
	Enveloped mono PlayBufs - Time Domain Transposition
	*/

	// ---------------------------------------------------------------------------------------------
	/*
	Implement implement a single synthDef similar to those found in Assignment 3a, but where
	the transposition is synthesized through the use of PitchShiftPA.

	As well as _refFreq_ and _minRefFreq_, expose _pitchRatio_ and _formantRatio_ as synthDef
	arguments.
	*/


);
